site_name: Inventory System Documentation
site_url: https://expressobits.com/inventory-system
repo_url: https://github.com/expressobits/inventory-system
repo_name: Inventory System
site_description: Documentation for the Inventory System project.
site_author: Rafael Correa
edit_uri: https://github.com/expressobits/inventory-system-docs/tree/main/docs/
plugins:
  - search
theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    # - navigation.prune
    - navigation.indexes
    - toc.follow
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
  font:
    text: Red Hat Text
    code: Red Hat Mono
  logo: assets/icon.svg
  palette: 
    # Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Dark mode
      primary: black
      accent: cyan
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Light mode
      primary: blue
      accent: cyan

extra:
  analytics:
    provider: google
    property: G-TBJYX8K1T0
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
      #combine_header_slug: true
  - admonition
  - pymdownx.details


nav:
  - Home: index.md
  - Getting Started:
    - getting_started/introduction.md
    - getting_started/installation.md
    - Quickstart:
      - getting_started/quickstart/create_database.md
      - getting_started/quickstart/add_item_to_database.md
      - getting_started/quickstart/add_items_to_inventory.md
  - Features:
    - features/database.md
    - features/item_definition.md
    - features/inventory.md
    - features/grid_inventory.md
  - Tutorials:
    - tutorials/how_to_test_multiplayer_demo.md
  - Contributing: 
    - contributing/index.md
    - contributing/cmake_support.md
      